# Numerical Analysis: Linear System

solve $Ax = b$

In [2]:
import numpy.linalg as la
import numpy.random as rn
import numpy as np

## Basic Operation

In [3]:
#making matrix
A = np.mat(rn.randn(4,4))
A

matrix([[-0.27987557, -0.12670132, -0.16353496, -0.78834768],
        [ 0.58489604, -1.08927466,  0.06368095,  1.08144153],
        [-0.4635079 ,  0.41858464, -0.90791568, -0.03356274],
        [-0.7944097 , -0.83572685,  2.24931594,  0.1405566 ]])

In [4]:
xt = np. mat(rn.randn(4,1))
xt

matrix([[-0.86424876],
        [ 1.02278295],
        [-0.54091067],
        [ 0.60827403]])

In [5]:
b = A*xt
b

matrix([[-0.27877945],
        [-0.99622013],
        [ 1.2993933 ],
        [-1.29938164]])

In [7]:
#solving system
x = la.solve(A,b)
x

matrix([[-0.86424876],
        [ 1.02278295],
        [-0.54091067],
        [ 0.60827403]])

In [8]:
#norm
la.norm(x-xt)

2.7194799110210365e-16

In [9]:
#make a int matrix
A = np.round(A*10)
A

matrix([[ -3.,  -1.,  -2.,  -8.],
        [  6., -11.,   1.,  11.],
        [ -5.,   4.,  -9.,  -0.],
        [ -8.,  -8.,  22.,   1.]])

In [10]:
#power
B = A**2
B

matrix([[  77.,   70., -153.,    5.],
        [-177.,   31.,  210., -158.],
        [  84.,  -75.,   95.,   84.],
        [-142.,  176., -168.,  -23.]])

In [11]:
#determinant
la.det(A)

-19057.99999999999

In [13]:
#id matrix
C = np.mat(np.identity(4))
C

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [15]:
#rank
la.matrix_rank(A)

4

In [18]:
#sun-matrix
E = A[:3,:3]
E

matrix([[ -3.,  -1.,  -2.],
        [  6., -11.,   1.],
        [ -5.,   4.,  -9.]])

In [19]:
v = A[:,0]
v

matrix([[-3.],
        [ 6.],
        [-5.],
        [-8.]])

In [21]:
u = A[:,2]
u

matrix([[-2.],
        [ 1.],
        [-9.],
        [22.]])

In [22]:
#interproduct
x = float(u.T*v)
x

-119.0

## Row Operation

In [23]:
I = np.mat(np.identity(3))
I

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
A = np.mat(np.round(rn.rand(3,3)*10))
A

matrix([[6., 1., 5.],
        [1., 1., 3.],
        [4., 0., 5.]])

In [25]:
#adding
E1 = I.copy() #reference passing, so use copy
E1[2,:] = E1[1,:]*3+E1[2,:]
E1 #IIIrow = IIrow *3 + IIIrow

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 3., 1.]])

In [27]:
B = E1*A
B

matrix([[ 6.,  1.,  5.],
        [ 1.,  1.,  3.],
        [ 7.,  3., 14.]])

In [28]:
#multiplying
E2 = I.copy()
E2[2,:] = E2[2,:]*2
E2

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 2.]])

In [29]:
B = E2*A
B

matrix([[ 6.,  1.,  5.],
        [ 1.,  1.,  3.],
        [ 8.,  0., 10.]])

In [30]:
#switching
E3 = I.copy()
E3[[0,1],:] = E3[[1,0],:]
E3

matrix([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])

In [31]:
B = E3*A
B

matrix([[1., 1., 3.],
        [6., 1., 5.],
        [4., 0., 5.]])

## Guass Elimination

In [66]:
def GaussElimination(A,b): #suppose A is squared and invertible
    m,n = A.shape
    
    # R is the rref
    R = np.mat(np.zeros([m,n+1])) #augmented matrix
    R[:,:n] = A
    R[:,n] = b
    
    for i in range(m):
        #find max element in the col i
        maxEc = abs(R[i,i])
        maxRow = i
        for k in range(i+1,m):
            if abs(R[k,i]) > maxEc:
                maxEc = R[k,i]
                maxRow = k
        
        #swap max row with current row
        R[[i, maxRow],i:] = R[[maxRow,i],i:] #from i col avoid move extra 0
        
        #make all rows below this one is 0
        for k in range(i+1,m):
            c = -float(R[k,i])/R[i,i]
            R[k,i:] = R[k,i:] + c*R[i,i:]
    
    #solve the equation for an upper triangular matrix
    x = np.mat(np.zeros([m,1]))
    for i in range(m-1,-1,-1): #from m-1(cause 0 is the first) to 0
        x[i] = float(R[i,-1])/R[i,i] #(m,n)/(m,m)
        for k in range(i-1,-1,-1):
            R[k,-1] -= R[k,i]*x[i]
    
    return x

In [56]:
A = np.mat(np.round(rn.rand(5,5)*10))
A

matrix([[ 5.,  5.,  5., 10.,  9.],
        [ 1.,  5.,  9.,  9.,  5.],
        [10.,  2.,  8.,  5.,  2.],
        [ 7.,  5.,  8.,  6.,  5.],
        [ 6.,  4.,  5.,  9.,  4.]])

In [57]:
xt = np.mat(np.round(rn.rand(5,1)*10))
xt

matrix([[5.],
        [8.],
        [3.],
        [2.],
        [5.]])

In [58]:
b = A*xt
b

matrix([[145.],
        [115.],
        [110.],
        [136.],
        [115.]])

In [67]:
x = GaussElimination(A,b)
x

matrix([[5.],
        [8.],
        [3.],
        [2.],
        [5.]])

## $PA=LU$ Decomposition

U is row operation

L is col operation

for swapping, A = LU, when there exists a need for row swapping, A = LPU'

where U' is swapped and P is the corresponding permutation matrix

for satisfy the PA = LU form, we multiply the P at left as PA = PLPU'

in this case L needs to do row and col swap.

In [76]:
def LU(A):
    m,n = A.shape
    U = A.copy()
    L = np.mat(np.identity(m))
    P = L.copy()
    
    for i in range(m):
        # find max element in the col i
        maxEc = abs(U[i,i])
        maxRow = i
        for k in range(i+1,m):
            if abs(U[k,i]) > maxEc:
                maxEc = U[k,i]
                maxRow = k
        
        #swap maximum row with current row
        U[[i, maxRow],:] = U[[maxRow,i],:]
        P[[i, maxRow],:] = P[[maxRow,i],:]
        L[[i, maxRow],:] = L[[maxRow,i],:]
        L[:,[i, maxRow]] = L[:,[maxRow,i]] #maintain low triangular form
        
        for k in range(i+1,m):
            c = -float(U[k,i])/U[i,i]
            #delete k row by i
            U[k,i:] = U[k,i:] + c*U[i,i:]
            #delete i col by k
            L[k:,i] = L[k:,i] - c*L[k:,k]
    
    return L,U,P

In [84]:
A = np.mat(np.round(rn.rand(5,5)*100))
A

matrix([[ 47.,  69.,   6.,  22.,  93.],
        [ 43.,  19.,  57.,  48.,  72.],
        [ 95.,  32.,  23.,  55.,  13.],
        [ 17.,  28.,  42.,  57., 100.],
        [ 55.,  48.,  88.,  40.,  95.]])

In [85]:
L,U,P = LU(A)

In [94]:
np.round(U)

matrix([[95., 32., 23., 55., 13.],
        [ 0., 53., -5., -5., 87.],
        [ 0., -0., 78., 11., 39.],
        [ 0.,  0.,  0., 44., 41.],
        [ 0.,  0.,  0.,  0., 19.]])

In [91]:
L

matrix([[1.        , 0.        , 0.        , 0.        , 0.        ],
        [0.49473684, 1.        , 0.        , 0.        , 0.        ],
        [0.57894737, 0.55434567, 1.        , 0.        , 0.        ],
        [0.17894737, 0.41892695, 0.51679748, 1.        , 0.        ],
        [0.45263158, 0.08493368, 0.60575185, 0.38633285, 1.        ]])

In [95]:
P

matrix([[0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.]])

In [96]:
P*A

matrix([[ 95.,  32.,  23.,  55.,  13.],
        [ 47.,  69.,   6.,  22.,  93.],
        [ 55.,  48.,  88.,  40.,  95.],
        [ 17.,  28.,  42.,  57., 100.],
        [ 43.,  19.,  57.,  48.,  72.]])

In [97]:
L*U

matrix([[ 95.,  32.,  23.,  55.,  13.],
        [ 47.,  69.,   6.,  22.,  93.],
        [ 55.,  48.,  88.,  40.,  95.],
        [ 17.,  28.,  42.,  57., 100.],
        [ 43.,  19.,  57.,  48.,  72.]])

## Solve System by Triangular Matrices

$Ax = b$

$PAx = Pb$

$LUx = Pb$

let $y=Ux$

$Ly = Pb$

$Ux = y$

the merit of this method is that doing calculation on triangular matrix is simple

In [110]:
def Forward(L,b):
    m,n = L.shape
    x = b.copy()
    for i in range(m):
        for k in range(i):
            x[i] -= L[i,k]*x[k] # in the first step i = 0 will not occur 
        x[i] = float(x[i])/L[i,i] # i, i is the pivot
    return x

def Backward(U,b):
    m,n = U.shape
    x = b.copy()
    for i in range(m-1,-1,-1):
        for k in range(m-1,i,-1):
            x[i] -= U[i,k]*x[k]
        x[i] = float(x[i])/U[i,i]
    return x

In [100]:
A

matrix([[ 47.,  69.,   6.,  22.,  93.],
        [ 43.,  19.,  57.,  48.,  72.],
        [ 95.,  32.,  23.,  55.,  13.],
        [ 17.,  28.,  42.,  57., 100.],
        [ 55.,  48.,  88.,  40.,  95.]])

In [103]:
xt = np.mat(np.round(rn.rand(5,1)*100))
xt

matrix([[ 1.],
        [27.],
        [51.],
        [72.],
        [92.]])

In [104]:
b = A*xt
b

matrix([[12356.],
        [13543.],
        [ 7288.],
        [16219.],
        [17459.]])

In [105]:
L,U,P = LU(A)

In [106]:
P*A

matrix([[ 95.,  32.,  23.,  55.,  13.],
        [ 47.,  69.,   6.,  22.,  93.],
        [ 55.,  48.,  88.,  40.,  95.],
        [ 17.,  28.,  42.,  57., 100.],
        [ 43.,  19.,  57.,  48.,  72.]])

In [107]:
L*U

matrix([[ 95.,  32.,  23.,  55.,  13.],
        [ 47.,  69.,   6.,  22.,  93.],
        [ 55.,  48.,  88.,  40.,  95.],
        [ 17.,  28.,  42.,  57., 100.],
        [ 43.,  19.,  57.,  48.,  72.]])

In [108]:
bp = P*b
bp

matrix([[ 7288.],
        [12356.],
        [17459.],
        [16219.],
        [13543.]])

In [111]:
y = Forward(L,bp) #solve y
y

matrix([[7288.        ],
        [8750.35789474],
        [8388.90853296],
        [6913.70409212],
        [1748.43308643]])

In [112]:
x = Backward(U,y) #solve x
x

matrix([[ 1.],
        [27.],
        [51.],
        [72.],
        [92.]])